### ISSUE TITLE
CSVがアップロードできない

### ISSUE THREAD

**Issue by y-yabe** [oizhaolei/electron-material-ui-mongo#1]
1105リリースのWindows版で動作確認したが、CSVファイルがアップロードできなかった。

CSVの内容は
id,name
id1,name1

![upload](https://user-images.githubusercontent.com/64675106/98326532-d3e01b80-2034-11eb-9587-4d7252b0fcfa.png)

**Comment by oizhaolei** [comment]
https://github.com/react-dropzone/react-dropzone/issues/391
https://stackoverflow.com/questions/60330532/dropzone-how-to-accept-csv-files

ＯＳによって、ＣＳＶの認識はちがうことがわかりました。

**Comment by oizhaolei** [comment]
修正したけど、Winがなくて、テストできません

**Comment by y-yabe** [comment]
1107バージョンで、CVSがアップロードできることを確認しました。
