### ISSUE TITLE
日本語なおしてください

### ISSUE THREAD

**Issue by yasdgs** [oizhaolei/electron-material-ui-mongo#2]
<img width="230" alt="スクリーンショット 2020-11-06 14 50 02" src="https://user-images.githubusercontent.com/63562385/98332927-04c74d00-2043-11eb-92a2-941c8a46d0dd.png">

パーソナルDB

と直してください

**Comment by oizhaolei** [comment]
直しました、今夜再リリースようにします。

**Comment by yasdgs** [comment]
直してくれてありがとうございます！(^O^)v
