### ISSUE TITLE
テーブル追加時のメモについて

### ISSUE THREAD

**Issue by y-yabe** [oizhaolei/electron-material-ui-mongo#5]
テーブル追加時、テーブル名とメモを入力するが、
「次へ」を押した次の画面に進んだ後、「前へ」を押して戻ると、
メモにテーブル名が入っている。

**Comment by oizhaolei** [comment]
たしかに、
まえきづいたことがありますが、修正することが忘れました。

今夜リリースします

**Comment by y-yabe** [comment]
1107版で動作を確認しました。
